# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

APPLY_FIXES: all
ENABLE:
  - PYTHON
DISABLE_LINTERS:
  - PYTHON_RUFF
  - PYTHON_PYLINT
  - PYTHON_BANDIT
  - PYTHON_PYRIGHT
  - PYTHON_MYPY
PYTHON_BLACK_ARGUMENTS: "--line-length 120"
PYTHON_FLAKE8_ARGUMENTS: "--max-line-length 120"
