name: Address Testing
on: 
  workflow_dispatch:
    inputs:
      suburb:
        required: true
        description: 'Suburb to check'
      state:
        required: true
        description: 'State of suburb to check'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 35000
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker
        run: |
          docker pull minus34/gnafloader:202302
          docker run -d --publish=5433:5432 minus34/gnafloader:202302

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r code/requirements.txt

      - name: Run program
        run: |
          python code/main.py "${{ github.event.inputs.suburb }}" "${{ github.event.inputs.state }}"

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: Updated region
          default_author: github_actions
          pull: '--rebase --autostash'

      - name: Run results
        run: |
          python code/results.py "${{ github.event.inputs.suburb }}" "${{ github.event.inputs.state }}"
  
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: Updated results
          default_author: github_actions
          pull: '--rebase --autostash'