name: Address Testing
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 45000
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker
        run: |
          docker pull minus34/gnafloader:latest
          docker run -d --publish=5433:5432 minus34/gnafloader:latest