name: Python package

on:
  push:
    branches: [ "main" ]
    paths:
      - 'code/**'
      - 'site/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'code/**'
      - 'site/**'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r code/requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          PYTHONPATH=code pytest tests --cov=code
